### ISSUE TITLE
Documentação: Formato na data na cotação por período está errado

### ISSUE THREAD

**Issue by aspeddro** [wilsonfreitas/python-bcb#12]
![image](https://github.com/wilsonfreitas/python-bcb/assets/16160544/47a25d63-6f60-4d27-aac3-5c44fd97b42a)

[API Docs](https://olinda.bcb.gov.br/olinda/servico/PTAX/versao/v1/documentacao)

![image](https://github.com/wilsonfreitas/python-bcb/assets/16160544/f9a79a6c-4d92-4685-a3bf-344dae3d017f)

Docs:
https://github.com/wilsonfreitas/python-bcb/blob/2a4ee313e63ee0e108f4abf18d01eba9f6ab9435/docs/odata.rst?plain=1#L326-L327

**Comment by wilsonfreitas** [comment]
Mas o formato é mês-dia-ano, o que está errado?

**Comment by aspeddro** [comment]
> É importante notar que as datas estão no formato dia/mês/ano e os números não são preenchidos com 0 para ter 2 dígitos.

**Comment by aspeddro** [comment]
Posso abrir um PR?

**Comment by wilsonfreitas** [comment]
Manda ver!
