### ISSUE TITLE
Endpoint ExpectativasMercadoInflacao12Meses não retorna inflação futura

### ISSUE THREAD

**Issue by guilhermeparreira** [wilsonfreitas/python-bcb#8]
Olá! Primeiro gostaria de parabenizar pelo pacote!

Tentei obter a expectativa de inflação mensal para os próximos 12 meses, mas ela retornou até Março somente:

```
from bcb import Expectativas
em = Expectativas()
ep = em.get_endpoint("ExpectativasMercadoInflacao12Meses")
print(ds_bacen['Data'].max())
2023-03-31
```

Está certo? Não deveria retornar até Março de 2024?

**Comment by wilsonfreitas** [comment]
Oi @guilhermeparreira

Dá uma olhada na documentação da API [aqui](https://olinda.bcb.gov.br/olinda/servico/Expectativas/versao/v1/documentacao#ExpectativasMercadoInflacao12Meses).

Neste *endpoint* a coluna `Data` é referente a **Data de cálculo da estatística**.
Com base nesta data de referência, a previsão é de 12 meses a frente.

**Comment by guilhermeparreira** [comment]
Obrigado pela resposta!!
Acabei de ler o link. E estudei as bases de dados disponíveis, e entendi. Cada projeção é feito de um jeito, com suas limitações..

Para pegar o IPCA mensal (histórico) eu vou pegar do `from bcb import sgs` e as projeções do `from bcb import Expectativas` e *endpoint* `ExpectativaMercadoMensais`

Muito bom o pacote.
